version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    container_name: wordpress_env_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
  webserver:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress_env
    tty: true
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
    volumes:
      - ./html:/var/www/html
volumes:
  dbdata: